included: # paths to include during linting. `--path` is ignored if present.
  - hackYourFuture
excluded:
  - Pods
  - hackYourFuture/hackYourFutureTests/
  - hackYourFuture/Resources/Generated

opt_in_rules:
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping # as error
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant # - to continue
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - literal_expression_end_indentation
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nesting
  - notification_center_detachment
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_first_last
  - statement_position
  - static_operator
  - strict_fileprivate
  - superfluous_disable_command
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_private_declaration
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_return
  - weak_delegate
  - yoda_condition
  # Unit Tests
  - empty_xctest_method
  - private_unit_test
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - xct_specific_matcher
  - xctfail_message

### Rules on / off

disabled_rules:
  - anyobject_protocol
  - conditional_returns_on_newline
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_header
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - missing_docs
  - multiline_arguments_brackets
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_grouping_extension
  - nslocalizedstring_key
  - object_literal
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - required_enum_case
  - sorted_imports
  - strong_iboutlet
  - vertical_whitespace_between_cases
  - vertical_whitespace_opening_braces
  # Unit tests
  - quick_discouraged_call
  - nimble_operator

### Rules configuration

# Vertical length

closure_body_length:
  warning: 30

function_body_length:
  warning: 35

type_body_length:
  warning: 300

file_length:
  warning: 500

function_parameter_count:
  warning: 3

# Horizontal length

line_length:
  warning: 150

trailing_whitespace:
  ignores_empty_lines: true

identifier_name:
  severity: warning
  min_length:
    warning: 1
  max_length:
    warning: 80

type_name:
  min_length:
    warning: 4
    error: 3
  max_length:
    warning: 100

# Misc

private_outlet:
  allow_private_set: true

cyclomatic_complexity:
  warning: 10

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 4

large_tuple:
  warning: 3

trailing_closure:
  only_single_muted_parameter: true

trailing_whitespace:
  ignores_empty_lines: true

empty_count:
    severity: warning
